name: shop-jee

services:
  postgres:
    image: postgres:14.4-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=shop-jee
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin